In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import os
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
import datetime


In [2]:
iris = load_iris()

In [3]:
iris.data, iris.target


(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [4]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [5]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [6]:
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)

In [7]:
iris_df['target'] = iris.target
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [8]:
scaler = StandardScaler()
x_scaled = scaler.fit_transform(iris.data)

In [9]:
x_scaled

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [10]:
y=iris.target.reshape(150,1)
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [11]:
encoder = OneHotEncoder(sparse_output=False)
y_encoded = encoder.fit_transform(y)
y_encoded

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y_encoded, test_size=0.2,)

In [13]:
x_train, x_test, y_train, y_test

(array([[ 7.95669016e-01, -1.31979479e-01,  1.16062026e+00,
          1.31719939e+00],
        [-1.50652052e+00,  1.24920112e+00, -1.56757623e+00,
         -1.31544430e+00],
        [-1.38535265e+00,  3.28414053e-01, -1.22655167e+00,
         -1.31544430e+00],
        [-1.50652052e+00,  3.28414053e-01, -1.34022653e+00,
         -1.31544430e+00],
        [ 4.32165405e-01, -3.62176246e-01,  3.08058854e-01,
          1.32509732e-01],
        [-2.94841818e-01, -8.22569778e-01,  2.51221427e-01,
          1.32509732e-01],
        [-1.73673948e-01,  3.09077525e+00, -1.28338910e+00,
         -1.05217993e+00],
        [ 2.24968346e+00,  1.70959465e+00,  1.67215710e+00,
          1.31719939e+00],
        [ 2.24968346e+00, -5.92373012e-01,  1.67215710e+00,
          1.05393502e+00],
        [-9.00681170e-01,  7.88807586e-01, -1.28338910e+00,
         -1.31544430e+00],
        [ 4.32165405e-01, -1.97355361e+00,  4.21733708e-01,
          3.95774101e-01],
        [-2.94841818e-01, -1.31979479e-01, 

In [14]:
inputs = tf.keras.Input(shape=(4,))
x = tf.keras.layers.Dense(10,activation='relu')(inputs)
x = tf.keras.layers.Dense(8,activation='relu')(x)
output = tf.keras.layers.Dense(3,activation='softmax')(x)
model = tf.keras.Model(inputs = inputs , outputs=output)

In [15]:
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 4)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 10)             │            50 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 8)              │            88 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 3)              │            27 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 165 (660.00 B)

 Trainable params: 165 (660.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
from tensorflow.keras.utils import plot_model


In [17]:
plot_model(model, show_shapes=True, show_layer_activations=True, show_dtype=True, show_layer_names=True, show_trainable=True)

You must install graphviz (see instructions at https://graphviz.gitlab.io/download/) for `plot_model` to work.


In [ ]:
model.layers[1].weights

[<Variable path=dense/kernel, shape=(4, 10), dtype=float32, value=[[ 0.19377548  0.48994935  0.03691971 -0.40989915  0.5285145   0.4255426
    0.48977387 -0.3927177  -0.5973413  -0.61397535]
  [-0.5757919   0.29030412  0.05701178  0.6277549  -0.04424304 -0.21220762
    0.07856381 -0.22055468 -0.37256318 -0.12789917]
  [ 0.17796516 -0.50238657 -0.33352467 -0.01790911 -0.41811448  0.18415862
   -0.39620766  0.5112437   0.6330379   0.5156305 ]
  [ 0.04292214 -0.4227932  -0.01479793 -0.63431734 -0.16149983  0.61532044
    0.32845372 -0.40235183 -0.1807077  -0.5766261 ]]>,
 <Variable path=dense/bias, shape=(10,), dtype=float32, value=[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]>]

In [25]:
model.layers[2].weights

[<Variable path=dense_1/kernel, shape=(10, 8), dtype=float32, value=[[ 0.08531237  0.12948322  0.486907    0.2782135   0.2764557   0.3671211
    0.2809968   0.05659717]
  [-0.4951931  -0.43440944 -0.13853198 -0.03759813 -0.37974918  0.4580171
    0.20553899 -0.29558218]
  [-0.23303095 -0.4112305   0.35572946 -0.26242316  0.50021374 -0.19463193
    0.29891086  0.46949255]
  [ 0.1810121   0.324584   -0.26557025  0.3480596  -0.17981121 -0.36264095
    0.44825864  0.2578562 ]
  [ 0.00405532  0.5329553  -0.32993093 -0.34135842  0.06786692 -0.4111976
    0.4445778  -0.04242182]
  [-0.48331603 -0.00869751 -0.4773198   0.12594378 -0.35858285  0.4107812
   -0.06724185 -0.27451262]
  [-0.40345144 -0.12384325 -0.16019028  0.3205101   0.16504979 -0.00780535
   -0.42080387 -0.36748844]
  [ 0.30322248  0.25999498  0.1608243   0.49269283 -0.23950261 -0.53273785
    0.18987775  0.13941753]
  [-0.49776292  0.23402286  0.5052496   0.45608592  0.08467025  0.05699015
   -0.1912668  -0.05979437]
  [-0.1471

In [27]:
model.layers[3].weights, model.layers[3].trainable_weights

([<Variable path=dense_2/kernel, shape=(8, 3), dtype=float32, value=[[ 0.01037008 -0.01295412 -0.4070175 ]
   [-0.39228544  0.0109089   0.64452595]
   [ 0.7030999  -0.40879506  0.5724794 ]
   [-0.0095427   0.12265414 -0.63501465]
   [-0.4530798   0.32696682 -0.3121402 ]
   [-0.02893811  0.16678059 -0.33227643]
   [ 0.57832927  0.7112618  -0.31243443]
   [ 0.15353364  0.42286783  0.4494664 ]]>,
  <Variable path=dense_2/bias, shape=(3,), dtype=float32, value=[0. 0. 0.]>],
 [<Variable path=dense_2/kernel, shape=(8, 3), dtype=float32, value=[[ 0.01037008 -0.01295412 -0.4070175 ]
   [-0.39228544  0.0109089   0.64452595]
   [ 0.7030999  -0.40879506  0.5724794 ]
   [-0.0095427   0.12265414 -0.63501465]
   [-0.4530798   0.32696682 -0.3121402 ]
   [-0.02893811  0.16678059 -0.33227643]
   [ 0.57832927  0.7112618  -0.31243443]
   [ 0.15353364  0.42286783  0.4494664 ]]>,
  <Variable path=dense_2/bias, shape=(3,), dtype=float32, value=[0. 0. 0.]>])

In [28]:
model.layers[3].bias

<Variable path=dense_2/bias, shape=(3,), dtype=float32, value=[0. 0. 0.]>

In [29]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [30]:
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)

In [31]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [36]:
log_dir = os.path.join("logs", "fit", datetime.datetime.now().strftime("%Y%m%d-%H%M%S"))
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

In [37]:
model.fit(x_train, y_train, epochs=20, batch_size=8, validation_split=0.20, callbacks=[tensorboard_callback])

Epoch 1/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 5s 151ms/step - accuracy: 0.9337 - loss: 0.2213 - val_accuracy: 0.9167 - val_loss: 0.2465
Epoch 2/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 45ms/step - accuracy: 0.9158 - loss: 0.2323 - val_accuracy: 0.9167 - val_loss: 0.2409
Epoch 3/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 58ms/step - accuracy: 0.9157 - loss: 0.2560 - val_accuracy: 0.9167 - val_loss: 0.2336
Epoch 4/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9235 - loss: 0.2065 - val_accuracy: 0.9167 - val_loss: 0.2276
Epoch 5/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 63ms/step - accuracy: 0.9123 - loss: 0.2178 - val_accuracy: 0.9583 - val_loss: 0.2185
Epoch 6/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 51ms/step - accuracy: 0.9403 - loss: 0.1923 - val_accuracy: 0.9583 - val_loss: 0.2124
Epoch 7/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 51ms/step - accuracy: 0.9308 - loss: 0.2074 - val_accuracy: 0.9583 - val_loss: 0.2057
Epoch 8/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.9412 - loss: 0.1860 - val_accuracy: 0.9583 - 

In [38]:
model.save("model.h5")

In [40]:
model.save("model.keras")

In [41]:
import joblib
joblib.dump(scaler, 'scaler.joblib')

['scaler.joblib']

In [42]:
model = tf.keras.models.load_model('model.h5')
scaler = joblib.load('scaler.joblib')

In [44]:
a = [[6.4,2.5,4.2,1.3]]
new_scaler = scaler.transform(a)

In [45]:
model.predict(new_scaler)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 285ms/step


array([[0.00616785, 0.88494015, 0.10889196]], dtype=float32)

In [53]:
iris.target_names[np.argmax(model.predict(new_scaler), axis=1)]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step


array(['versicolor'], dtype='<U10')

In [54]:
def iris_prediction(new_data):
    new_scaler = scaler.transform(new_data)
    class_label = iris.target_names[np.argmax(model.predict(new_scaler), axis=1)]
    return class_label

In [63]:
iris_prediction([[1.4,2.1,5.2,3.3]])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step


array(['virginica'], dtype='<U10')

In [64]:
import keras_tuner as kt


In [67]:
def build_model(hp):
    model = tf.keras.Sequential()
    model.add(tf.keras.layers.Input(shape=(4,)))

    for i in range(hp.Int("num_layers",1,3)):
        model.add(tf.keras.layers.Dense(
            units=hp.Int(f"units_{i}", min_value=4, max_value=32, step=4),
            activation='relu'
        ))

    model.add(tf.keras.layers.Dense(3, activation='softmax'))

    lr = hp.Choice("learning_rate", [1e-2, 1e-3, 1e-4])
    model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=lr),
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])
    return model    

In [68]:
tuner = kt.RandomSearch(
    build_model,
    objective = 'val_accuracy',
    max_trials=5,
    executions_per_trial=2,
    directory = 'kt_logs',
    project_name = 'iris_tuning'
)

In [70]:
tuner.search(x_train, y_train, epochs=20, validation_split=0.2)
best_model = tuner.get_best_hyperparameters(1)[0]

Trial 5 Complete [00h 00m 13s]
val_accuracy: 0.4375

Best val_accuracy So Far: 0.9791666567325592
Total elapsed time: 00h 01m 48s


In [71]:
tuner.results_summary()

Results summary
Results in kt_logs\iris_tuning
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 3 summary
Hyperparameters:
num_layers: 2
units_0: 12
learning_rate: 0.01
units_1: 12
Score: 0.9791666567325592

Trial 2 summary
Hyperparameters:
num_layers: 2
units_0: 8
learning_rate: 0.001
units_1: 4
Score: 0.5416666567325592
Traceback (most recent call last):
  File "g:\Projects\Deep_Learning_Project\myvenv\lib\site-packages\keras_tuner\src\engine\base_tuner.py", line 274, in _try_run_and_update_trial
    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)
  File "g:\Projects\Deep_Learning_Project\myvenv\lib\site-packages\keras_tuner\src\engine\base_tuner.py", line 239, in _run_and_update_trial
    results = self.run_trial(trial, *fit_args, **fit_kwargs)
  File "g:\Projects\Deep_Learning_Project\myvenv\lib\site-packages\keras_tuner\src\engine\tuner.py", line 314, in run_trial
    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)
  Fil